url: //tingtaoxiaozhu.github.io

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    

regenerate: true
incremental: true

plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 50
paginate_path: "page:num"

excerpt_separator:  '<!-- more -->'